In [1]:
import numpy as np
import json

In [2]:
ts_info_file = '/mnt/data/waymo/mot_demo/demo_data/ts_info/segment-10203656353524179475_7625_000_7645_000_with_camera_labels.json'

In [5]:
ego_info_file = '/mnt/data/waymo/mot_demo/demo_data/ego_info/segment-10203656353524179475_7625_000_7645_000_with_camera_labels.npz'
pc_file = '/mnt/data/waymo/mot_demo/demo_data/pc/raw_pc/segment-10203656353524179475_7625_000_7645_000_with_camera_labels.npz'
dt_file = '/mnt/data/waymo/mot_demo/demo_data/detection/cp/dets/segment-10203656353524179475_7625_000_7645_000_with_camera_labels.npz'
res_file = '/mnt/data/waymo/mot_demo/demo_data/mot_results/demo_cp/summary/vehicle/segment-10203656353524179475_7625_000_7645_000_with_camera_labels.npz'

In [6]:
ts_info = json.load(open(ts_info_file))
ego_info = np.load(ego_info_file)
pc = np.load(pc_file)
dt = np.load(dt_file, allow_pickle=True)
res = np.load(res_file, allow_pickle=True)

In [9]:
len(ts_info)

198

In [13]:
ego_info['0'].shape

(4, 4)

In [14]:
len(ego_info)

198

In [12]:
pc[pc.files[0]].shape

(124102, 3)

In [10]:
for ele in pc.files:
    print(np.max(pc[ele], axis=0))

[76.29541  74.44385   5.454527]
[76.04932 74.5249   5.46514]
[75.68335   74.70264    6.5446477]
[76.05591 74.69092  5.25062]
[75.69971  74.61133   5.323639]
[75.81348  74.51758   5.316231]
[76.196045  74.40137    5.3709564]
[75.41821   73.96875    5.2577744]
[76.21997  73.71045   5.261236]
[76.14697   72.99609    5.3428307]
[76.10205   73.129395   5.3777266]
[74.9043    74.45557    5.3569717]
[75.27515   72.42822    5.2753506]
[76.04492   72.06787    5.3600655]
[75.82544  71.48926   5.372904]
[76.34473   71.33789    5.3481464]
[76.4126    70.950195   5.3225174]
[75.82446  70.095215  5.340481]
[76.1499    69.81641    5.4436703]
[76.012695 68.97754   5.393198]
[76.33008  74.748535  5.341679]
[75.862305 73.21631   5.336058]
[75.871826  71.160645   5.9074855]
[75.88916  74.17236   5.638305]
[75.69946   74.31152    5.3860416]
[75.78833 74.52197  5.34174]
[76.17529   74.71924    5.1929917]
[75.75391   74.72168    5.1658716]
[75.951416  74.90967    5.1657715]
[75.56738  74.83203   5.252678]
[

In [11]:
for ele in pc.files:
    print(np.min(pc[ele], axis=0))

[-73.801025  -74.21045    -4.6140594]
[-73.59326  -74.61963   -4.617485]
[-73.410645 -74.731445  -4.462303]
[-72.167725 -74.631836  -4.545086]
[-73.42822  -71.49609   -4.800762]
[-71.16284   -72.02197    -4.9216995]
[-72.006836  -73.76807    -4.6977158]
[-71.085205 -71.6626    -4.195408]
[-71.98218   -74.086914   -3.8295689]
[-71.61304   -66.6001     -3.4467468]
[-73.90381   -72.79541    -3.3410382]
[-74.158936  -69.26758    -3.0494041]
[-73.81665   -69.180176   -2.8349524]
[-73.76782  -68.898926  -2.965621]
[-74.23291   -68.39111    -2.5520287]
[-72.42114   -57.52881    -2.5594635]
[-72.318115  -54.75049    -2.1656265]
[-73.90137  -52.776855  -2.187666]
[-74.26489  -49.841797  -1.830555]
[-71.93042   -47.89502    -1.7855501]
[-72.41504   -44.941895   -1.7647117]
[-74.37842   -39.645996   -1.3095889]
[-73.38428   -37.25       -1.3257504]
[-74.08252   -36.250977   -1.4133644]
[-73.930664  -59.38037    -1.1176949]
[-74.08154   -59.240723   -1.1144867]
[-74.07837    -57.17578     -0.84851

In [29]:
dt.files

['bboxes', 'types']

In [30]:
res.files

['ids', 'bboxes', 'states']

In [25]:
pc['111'].shape

(132921, 3)

In [55]:
dt['bboxes'][160][0]

array([-24.55960083,  15.86034012,   0.89315742,  -3.11765575,
         7.06777048,   2.69797325,   2.27727723,   0.93184638])

In [91]:
dt['types'][180]

[1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 4,
 1,
 2,
 1,
 4,
 1,
 1,
 1,
 2,
 1,
 4,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 4,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 4,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 4,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 4,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1]

In [68]:
len(res['ids'][1])

9

In [69]:
len(res['bboxes'][1])

9

In [72]:
res['states'][0]

['alive_1_0',
 'alive_1_0',
 'alive_1_0',
 'alive_1_0',
 'alive_1_0',
 'alive_1_0',
 'alive_1_0',
 'alive_1_0']

In [74]:
res_pd_file = '/mnt/data/waymo/mot_demo/mot_results/demo/summary/pedestrian/segment-10203656353524179475_7625_000_7645_000_with_camera_labels.npz'

In [75]:
res_pd = np.load(res_pd_file, allow_pickle=True)

In [76]:
res_pd.files

['ids', 'bboxes', 'states']

In [90]:
res_pd['ids']

array([list([]), list([]), list([]), list([]), list([]), list([]),
       list([]), list([0]), list([0]), list([0, 1]), list([0, 1, 2]),
       list([0, 1, 2]), list([0, 1, 2]), list([1, 2]), list([1]),
       list([1]), list([1]), list([]), list([]), list([]), list([]),
       list([3]), list([3]), list([3]), list([3]), list([3]), list([3]),
       list([3]), list([3]), list([]), list([4]), list([4]), list([4]),
       list([4]), list([4]), list([]), list([]), list([]), list([]),
       list([]), list([]), list([]), list([5]), list([5]), list([]),
       list([]), list([]), list([]), list([6]), list([6]), list([]),
       list([]), list([]), list([]), list([]), list([]), list([]),
       list([]), list([]), list([7]), list([7, 8, 9]), list([8, 9, 10]),
       list([8, 9, 10]), list([8, 9, 10]), list([8, 9, 10, 11]),
       list([8, 9, 10, 11]), list([8, 9, 10, 11]),
       list([8, 9, 10, 11, 12]), list([8, 9, 10, 11, 12]),
       list([8, 9, 10, 12]), list([8, 9, 10, 12]), list([8, 9

In [81]:
res_cc_file = '/mnt/data/waymo/mot_demo/mot_results/demo/summary/cyclist/segment-10203656353524179475_7625_000_7645_000_with_camera_labels.npz'

In [85]:
res_cc = np.load(res_cc_file, allow_pickle=True)

In [89]:
res_cc['states']

array([], shape=(198, 0), dtype=float64)