In [1]:
import numpy as np
import json
import time
import datetime
import pickle

In [2]:
ts_info_file = '/mnt/data/waymo/mot_demo/demo_data/ts_info/segment-10203656353524179475_7625_000_7645_000_with_camera_labels.json'
ego_info_file = '/mnt/data/waymo/mot_demo/demo_data/ego_info/segment-10203656353524179475_7625_000_7645_000_with_camera_labels.npz'
pc_file = '/mnt/data/waymo/mot_demo/demo_data/pc/raw_pc/segment-10203656353524179475_7625_000_7645_000_with_camera_labels.npz'
dt_file = "/mnt/data/waymo/mot/detection/pvrcnnplusplus/dets/segment-10203656353524179475_7625_000_7645_000_with_camera_labels.npz"
res_file = '/mnt/data/waymo/mot_demo/demo_data/mot_results/demo_cp/summary/vehicle/segment-10203656353524179475_7625_000_7645_000_with_camera_labels.npz'

In [3]:
ts_info = json.load(open(ts_info_file))
ego_info = np.load(ego_info_file)
pc = np.load(pc_file)
dt = np.load(dt_file, allow_pickle=True)
res = np.load(res_file, allow_pickle=True)

In [32]:
timestamp = datetime.datetime.fromtimestamp(ts_info[0] * 1e-6)

In [36]:
ego_info.files

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99',
 '100',
 '101',
 '102',
 '103',
 '104',
 '105',
 '106',
 '107',
 '108',
 '109',
 '110',
 '111',
 '112',
 '113',
 '114',
 '115',
 '116',
 '117',
 '118',
 '119',
 '120',
 '121',
 '122',
 '123',
 '124',
 '125',
 '126',
 '127',
 '128',
 '129',
 '130',
 '131',
 '132',
 '133',
 '134',
 '135',
 '136',
 '137',
 '138'

In [12]:
pc[pc.files[0]].shape

(124102, 3)

In [51]:
dt

['bboxes', 'types']

In [19]:
np.array([[1,2,2],[1,3,3]])[0]

array([1, 2, 2])

In [15]:
dt['types'][0]

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 2]

In [40]:
res.files

['ids', 'bboxes', 'states']

In [48]:
len(res['bboxes'][100])

15

In [47]:
res['ids'][100]

[5, 17, 18, 19, 20, 21, 22, 23, 24, 26, 27, 28, 29, 30, 31]

In [10]:
for ele in pc.files:
    print(np.max(pc[ele], axis=0))

[76.29541  74.44385   5.454527]
[76.04932 74.5249   5.46514]
[75.68335   74.70264    6.5446477]
[76.05591 74.69092  5.25062]
[75.69971  74.61133   5.323639]
[75.81348  74.51758   5.316231]
[76.196045  74.40137    5.3709564]
[75.41821   73.96875    5.2577744]
[76.21997  73.71045   5.261236]
[76.14697   72.99609    5.3428307]
[76.10205   73.129395   5.3777266]
[74.9043    74.45557    5.3569717]
[75.27515   72.42822    5.2753506]
[76.04492   72.06787    5.3600655]
[75.82544  71.48926   5.372904]
[76.34473   71.33789    5.3481464]
[76.4126    70.950195   5.3225174]
[75.82446  70.095215  5.340481]
[76.1499    69.81641    5.4436703]
[76.012695 68.97754   5.393198]
[76.33008  74.748535  5.341679]
[75.862305 73.21631   5.336058]
[75.871826  71.160645   5.9074855]
[75.88916  74.17236   5.638305]
[75.69946   74.31152    5.3860416]
[75.78833 74.52197  5.34174]
[76.17529   74.71924    5.1929917]
[75.75391   74.72168    5.1658716]
[75.951416  74.90967    5.1657715]
[75.56738  74.83203   5.252678]
[

In [11]:
for ele in pc.files:
    print(np.min(pc[ele], axis=0))

[-73.801025  -74.21045    -4.6140594]
[-73.59326  -74.61963   -4.617485]
[-73.410645 -74.731445  -4.462303]
[-72.167725 -74.631836  -4.545086]
[-73.42822  -71.49609   -4.800762]
[-71.16284   -72.02197    -4.9216995]
[-72.006836  -73.76807    -4.6977158]
[-71.085205 -71.6626    -4.195408]
[-71.98218   -74.086914   -3.8295689]
[-71.61304   -66.6001     -3.4467468]
[-73.90381   -72.79541    -3.3410382]
[-74.158936  -69.26758    -3.0494041]
[-73.81665   -69.180176   -2.8349524]
[-73.76782  -68.898926  -2.965621]
[-74.23291   -68.39111    -2.5520287]
[-72.42114   -57.52881    -2.5594635]
[-72.318115  -54.75049    -2.1656265]
[-73.90137  -52.776855  -2.187666]
[-74.26489  -49.841797  -1.830555]
[-71.93042   -47.89502    -1.7855501]
[-72.41504   -44.941895   -1.7647117]
[-74.37842   -39.645996   -1.3095889]
[-73.38428   -37.25       -1.3257504]
[-74.08252   -36.250977   -1.4133644]
[-73.930664  -59.38037    -1.1176949]
[-74.08154   -59.240723   -1.1144867]
[-74.07837    -57.17578     -0.84851

In [25]:
pc['111'].shape

(132921, 3)

In [55]:
dt['bboxes'][160][0]

array([-24.55960083,  15.86034012,   0.89315742,  -3.11765575,
         7.06777048,   2.69797325,   2.27727723,   0.93184638])

In [22]:
dt['types'][180][0]

1

In [68]:
len(res['ids'][1])

9

In [69]:
len(res['bboxes'][1])

9

In [72]:
res['states'][0]

['alive_1_0',
 'alive_1_0',
 'alive_1_0',
 'alive_1_0',
 'alive_1_0',
 'alive_1_0',
 'alive_1_0',
 'alive_1_0']

In [28]:
pc['0'].shape

(124102, 3)

In [2]:
lidar2ego_f = '/mnt/data/zlidar/lidar-sample/lidar2egos.pkl'
lidar2ego_f = open(lidar2ego_f, 'rb')
lidar2ego = pickle.load(lidar2ego_f)
lidar2ego = lidar2ego.values


In [4]:
lidar2ego[0]

array([ 1.06805951e-03, -9.99857909e-01, -1.68729842e-02,  1.07098034e+00,
        9.99810288e-01,  7.39604419e-04,  1.94593057e-02, -4.65892236e-02,
       -1.94438655e-02, -1.68905455e-02,  9.99667673e-01,  1.95128934e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00])

In [2]:
vh_folder = '/mnt/data/zlidar/lidar-sample/mot_results/segment1/summary/vehicle/segment1.npz'
pd_folder = '/mnt/data/zlidar/lidar-sample/mot_results/segment1/summary/pedestrian/segment1.npz'
cc_folder = '/mnt/data/zlidar/lidar-sample/mot_results/segment1/summary/cyclist/segment1.npz'
vh_data = np.load(vh_folder, allow_pickle=True)
pd_data = np.load(pd_folder, allow_pickle=True)
cc_data = np.load(cc_folder, allow_pickle=True)

In [83]:
len(vh_data['ids'][-1])

12

In [75]:
pd_data['ids'][-1]

[0, 1, 6, 16, 19]

In [76]:
cc_data['ids'][-1]

[]

In [59]:
track_file1 = open('/mnt/data/zlidar/lidar-sample/mot_results/segment1/summary/track_results_bk.pkl', 'rb')
track_file2 = open('/mnt/data/zlidar/lidar-sample/mot_results/segment1/summary/track_results.pkl', 'rb')
det_file = open('/mnt/data/zlidar/lidar-sample/detection/segment1.pkl', 'rb')

In [60]:

track_data1 = pickle.load(track_file1)
track_data2 = pickle.load(track_file2)
det_data = pickle.load(det_file)

In [55]:
track_data1.keys()

dict_keys(['bboxes', 'types', 'ids', 'names'])

In [35]:
track_data2.keys()

dict_keys(['bboxes', 'types', 'ids', 'names'])

In [43]:
len(track_data2['bboxes'])

27

In [78]:
track_data1['bboxes'][-1].shape

(17, 8)

In [81]:
track_data2['ids'][-1]

[0, 1, 3, 5, 6, 7, 10, 13, 15, 16, 17, 18, 0, 1, 6, 16, 19]

In [84]:
det_data['bboxes'][-1].shape

(33, 8)

In [86]:
track_data1['names'] == track_data2['names'] == det_data['names']

True

In [87]:
det_data.keys()

dict_keys(['bboxes', 'types', 'names'])